name: est_covoit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.2.1
  googleapis_auth: ^1.4.1
  
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  geocoding: ^2.1.1
  url_launcher: ^6.2.5
  intl: ^0.20.2
  http: ^1.6.0
  provider: ^6.1.5+1
  shared_preferences: ^2.2.0
  image_picker: ^1.2.1
  firebase_storage: ^12.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/service_account.json

# Config dyal l-icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21

